# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [1]:
import numpy as np

squaremeter = np.array([150, 200, 100, 90, 80, 95, 120, 300, 220, 180])
rooms = np.array([1,3,4,5,4,3,1,5,6,2])
price = np.array([180000,240000,350000,650000,655111,950000,450000,2560000,688880,600000])
arr=np.array([squaremeter,rooms,price])


2. Transpose the array you have created, so that every line can represent features of one house.

In [2]:
arr.transpose()

array([[    150,       1,  180000],
       [    200,       3,  240000],
       [    100,       4,  350000],
       [     90,       5,  650000],
       [     80,       4,  655111],
       [     95,       3,  950000],
       [    120,       1,  450000],
       [    300,       5, 2560000],
       [    220,       6,  688880],
       [    180,       2,  600000]])

3. Display the shape of the array and explain what it means.

In [3]:
arr.shape  ##we see how many rows and columns our data consists of

(3, 10)

4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [7]:
def tab(row,column):
    arr= list()#np.full((row,column),1)

    for x in range(1,row+1):
        for y in range(1,column+1):
            if(x%2==0 and y%2==0): 
                arr.append(0)
            else: 
                arr.append(1)
            
    arr=np.array(arr)
    print(arr.reshape(row,column))
tab(6,5)

[[1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 1 1]
 [1 0 1 0 1]]
