In [15]:
import numpy as np
import random
import sys

In [16]:
def createrandom():
    rowlist=list()
    collist=list()
    rcsum=0
    for rw in range(4):
        for clmn in range(4):
            if arr[rw,clmn]==0:
                rowlist.append(rw) 
                collist.append(clmn)
            else:
                rcsum+=1
                if (rcsum==16):
                    print(rcsum)
                    print("Game Over")
                    print("Your Score : ", np.sum(arr))
                    sys.exit(1)
    
    r=random.randint(0,len(rowlist)-1)
    arr[rowlist[r],collist[r]]=2

  


In [17]:
def start():
    step= input("Left: l , Right: r , Up: u , Down: d | Please Select:")
    if(step=="l"):
        for rw in range(4):
            collocation=list()
            for clmn in range(4):
                if arr[rw,clmn]!=0:
                    collocation.append(clmn)
            if(len(collocation)==1): 
                arr[rw,0]=arr[rw,collocation[0]]
                arr[rw,1]=0
                arr[rw,2]=0
                arr[rw,3]=0
            elif(len(collocation)==2):
                if arr[rw,collocation[0]]==arr[rw,collocation[1]]:
                    arr[rw,0]=arr[rw,collocation[0]]+arr[rw,collocation[1]]
                    arr[rw,1]=0
                    arr[rw,2]=0
                    arr[rw,3]=0
                else:
                    arr[rw,0]=arr[rw,collocation[0]]
                    arr[rw,1]=arr[rw,collocation[1]]
                    arr[rw,2]=0
                    arr[rw,3]=0
            elif(len(collocation)==3):       
                if arr[rw,collocation[0]]==arr[rw,collocation[1]]:
                    arr[rw,0]=arr[rw,collocation[0]]+arr[rw,collocation[1]]
                    arr[rw,1]=arr[rw,collocation[2]]
                    arr[rw,2]=0
                    arr[rw,3]=0

                elif arr[rw,collocation[1]]==arr[rw,collocation[2]]:
                    arr[rw,0]=arr[rw,collocation[0]]
                    arr[rw,1]=arr[rw,collocation[1]]+arr[rw,collocation[2]]
                    arr[rw,2]=0
                    arr[rw,3]=0
                else:
                    arr[rw,0]=arr[rw,collocation[0]]
                    arr[rw,1]=arr[rw,collocation[1]]
                    arr[rw,2]=arr[rw,collocation[2]]
                    arr[rw,3]=0
            elif(len(collocation)==4):
                if arr[rw,collocation[0]]==arr[rw,collocation[1]] and arr[rw,collocation[2]]==arr[rw,collocation[3]]:
                    arr[rw,0]=arr[rw,collocation[0]]+arr[rw,collocation[1]]
                    arr[rw,1]=arr[rw,collocation[2]]+arr[rw,collocation[3]]
                    arr[rw,2]=0
                    arr[rw,3]=0
                elif arr[rw,collocation[0]]==arr[rw,collocation[1]]:
                    arr[rw,0]=arr[rw,collocation[0]]+arr[rw,collocation[1]]
                    arr[rw,1]=arr[rw,collocation[2]]
                    arr[rw,2]=arr[rw,collocation[3]]
                    arr[rw,3]=0
                elif arr[rw,collocation[1]]==arr[rw,collocation[2]]:
                    arr[rw,0]=arr[rw,collocation[0]]
                    arr[rw,1]=arr[rw,collocation[1]]+arr[rw,collocation[2]]
                    arr[rw,2]=arr[rw,collocation[3]]
                    arr[rw,3]=0
                elif arr[rw,collocation[2]]==arr[rw,collocation[3]]:
                    arr[rw,0]=arr[rw,collocation[0]]
                    arr[rw,1]=arr[rw,collocation[1]]
                    arr[rw,2]=arr[rw,collocation[2]]+arr[rw,collocation[3]]
                    arr[rw,3]=0
                else:
                    arr[rw,0]=arr[rw,collocation[0]]
                    arr[rw,1]=arr[rw,collocation[1]]
                    arr[rw,2]=arr[rw,collocation[2]]
                    arr[rw,3]=arr[rw,collocation[3]]
    elif(step=="r"):
        for rw in range(4):
            collocation=list()
            for clmn in range(4):
                if arr[rw,clmn]!=0:
                    collocation.append(clmn)
            if(len(collocation)==1): 
                arr[rw,3]=arr[rw,collocation[0]]
                arr[rw,2]=0
                arr[rw,1]=0
                arr[rw,0]=0
            elif(len(collocation)==2):
                if arr[rw,collocation[0]]==arr[rw,collocation[1]]:
                    arr[rw,3]=arr[rw,collocation[0]]+arr[rw,collocation[1]]
                    arr[rw,2]=0
                    arr[rw,1]=0
                    arr[rw,0]=0
                else:
                    arr[rw,3]=arr[rw,collocation[1]]
                    arr[rw,2]=arr[rw,collocation[0]]
                    arr[rw,1]=0
                    arr[rw,0]=0
            elif(len(collocation)==3):       
                if arr[rw,collocation[1]]==arr[rw,collocation[2]]:
                    arr[rw,3]=arr[rw,collocation[1]]+arr[rw,collocation[2]]
                    arr[rw,2]=arr[rw,collocation[0]]
                    arr[rw,1]=0
                    arr[rw,0]=0
            
                elif arr[rw,collocation[0]]==arr[rw,collocation[1]]:
                    arr[rw,3]=arr[rw,collocation[2]]
                    arr[rw,2]=arr[rw,collocation[0]]+arr[rw,collocation[1]]
                    arr[rw,1]=0
                    arr[rw,0]=0

                else:
                    arr[rw,3]=arr[rw,collocation[2]]
                    arr[rw,2]=arr[rw,collocation[1]]
                    arr[rw,1]=arr[rw,collocation[0]]
                    arr[rw,0]=0

            elif(len(collocation)==4):
                if arr[rw,collocation[0]]==arr[rw,collocation[1]] and arr[rw,collocation[2]]==arr[rw,collocation[3]]:
                    arr[rw,3]=arr[rw,collocation[2]]+arr[rw,collocation[3]]
                    arr[rw,2]=arr[rw,collocation[0]]+arr[rw,collocation[1]]
                    arr[rw,1]=0
                    arr[rw,0]=0

                elif arr[rw,collocation[2]]==arr[rw,collocation[3]]:
                    arr[rw,3]=arr[rw,collocation[2]]+arr[rw,collocation[3]]
                    arr[rw,2]=arr[rw,collocation[1]]
                    arr[rw,1]=arr[rw,collocation[0]]
                    arr[rw,0]=0
                    
                elif arr[rw,collocation[1]]==arr[rw,collocation[2]]:
                    arr[rw,3]=arr[rw,collocation[3]]
                    arr[rw,2]=arr[rw,collocation[1]]+arr[rw,collocation[2]]
                    arr[rw,1]=arr[rw,collocation[0]]
                    arr[rw,0]=0
                    
                elif arr[rw,collocation[0]]==arr[rw,collocation[1]]:
                    arr[rw,3]=arr[rw,collocation[3]]
                    arr[rw,2]=arr[rw,collocation[2]]
                    arr[rw,1]=arr[rw,collocation[0]]+arr[rw,collocation[1]]
                    arr[rw,0]=0

                else:
                    arr[rw,3]=arr[rw,collocation[3]]
                    arr[rw,2]=arr[rw,collocation[2]]
                    arr[rw,1]=arr[rw,collocation[1]]
                    arr[rw,0]=arr[rw,collocation[0]]
    elif(step=="u"):
        for clmn in range(4):
            rowlocation=list()
            for rw in range(4):
                if arr[rw,clmn]!=0:
                    rowlocation.append(rw)
            if(len(rowlocation)==1): 
                arr[0,clmn]=arr[rowlocation[0],clmn]
                arr[1,clmn]=0
                arr[2,clmn]=0
                arr[3,clmn]=0
            elif(len(rowlocation)==2):
                if arr[rowlocation[0],clmn]==arr[rowlocation[1],clmn]:
                    arr[0,clmn]=arr[rowlocation[0],clmn]+arr[rowlocation[1],clmn]
                    arr[1,clmn]=0
                    arr[2,clmn]=0
                    arr[3,clmn]=0
                else:
                    arr[0,clmn]=arr[rowlocation[0],clmn]
                    arr[1,clmn]=arr[rowlocation[1],clmn]
                    arr[2,clmn]=0
                    arr[3,clmn]=0
            elif(len(rowlocation)==3):       
                if arr[rowlocation[0],clmn]==arr[rowlocation[1],clmn]:
                    arr[0,clmn]=arr[rowlocation[0],clmn]+arr[rowlocation[1],clmn]
                    arr[1,clmn]=arr[rowlocation[2],clmn]
                    arr[2,clmn]=0
                    arr[3,clmn]=0

                elif arr[rowlocation[1],clmn]==arr[rowlocation[2],clmn]:
                    arr[0,clmn]=arr[rowlocation[0],clmn]
                    arr[1,clmn]=arr[rowlocation[1],clmn]+arr[rowlocation[2],clmn]
                    arr[2,clmn]=0
                    arr[3,clmn]=0
                else:
                    arr[0,clmn]=arr[rowlocation[0],clmn]
                    arr[1,clmn]=arr[rowlocation[1],clmn]
                    arr[2,clmn]=arr[rowlocation[2],clmn]
                    arr[3,clmn]=0
            elif(len(rowlocation)==4):
                if arr[rowlocation[0],clmn]==arr[rowlocation[1],clmn] and arr[rowlocation[2],clmn]==arr[rowlocation[3],clmn]:
                    arr[0,clmn]=arr[rowlocation[0],clmn]+arr[rowlocation[1],clmn]
                    arr[1,clmn]=arr[rowlocation[2],clmn]+arr[rowlocation[3],clmn]
                    arr[2,clmn]=0
                    arr[3,clmn]=0
                elif arr[rowlocation[0],clmn]==arr[rowlocation[1],clmn]:
                    arr[0,clmn]=arr[rowlocation[0],clmn]+arr[rowlocation[1],clmn]
                    arr[1,clmn]=arr[rowlocation[2],clmn]
                    arr[2,clmn]=arr[rowlocation[3],clmn]
                    arr[3,clmn]=0
                elif arr[rowlocation[1],clmn]==arr[rowlocation[2],clmn]:
                    arr[0,clmn]=arr[rowlocation[0],clmn]
                    arr[1,clmn]=arr[rowlocation[1],clmn]+arr[rowlocation[2],clmn]
                    arr[2,clmn]=arr[rowlocation[3],clmn]
                    arr[3,clmn]=0
                elif arr[rowlocation[2],clmn]==arr[rowlocation[3],clmn]:
                    arr[0,clmn]=arr[rowlocation[0],clmn]
                    arr[1,clmn]=arr[rowlocation[1],clmn]
                    arr[2,clmn]=arr[rowlocation[2],clmn]+arr[rowlocation[3],clmn]
                    arr[3,clmn]=0
                else:
                    arr[0,clmn]=arr[rowlocation[0],clmn]
                    arr[1,clmn]=arr[rowlocation[1],clmn]
                    arr[2,clmn]=arr[rowlocation[2],clmn]
                    arr[3,clmn]=arr[rowlocation[3],clmn]  
    elif(step=="d"):
        for clmn in range(4):
            rowlocation=list()
            for rw in range(4):
                if arr[rw,clmn]!=0:
                    rowlocation.append(rw)
            if(len(rowlocation)==1): 
                arr[3,clmn]=arr[rowlocation[0],clmn]
                arr[2,clmn]=0
                arr[1,clmn]=0
                arr[0,clmn]=0
            elif(len(rowlocation)==2):
                if arr[rowlocation[0],clmn]==arr[rowlocation[1],clmn]:
                    arr[3,clmn]=arr[rowlocation[0],clmn]+arr[rowlocation[1],clmn]
                    arr[2,clmn]=0
                    arr[1,clmn]=0
                    arr[0,clmn]=0
                else:
                    arr[3,clmn]=arr[rowlocation[1],clmn]
                    arr[2,clmn]=arr[rowlocation[0],clmn]
                    arr[1,clmn]=0
                    arr[0,clmn]=0
            elif(len(rowlocation)==3):       
                if arr[rowlocation[1],clmn]==arr[rowlocation[2],clmn]:
                    arr[3,clmn]=arr[rowlocation[1],clmn]+arr[rowlocation[2],clmn]
                    arr[2,clmn]=arr[rowlocation[0],clmn]
                    arr[1,clmn]=0
                    arr[0,clmn]=0
                
                elif arr[rowlocation[0],clmn]==arr[rowlocation[1],clmn]:
                    arr[3,clmn]=arr[rowlocation[2],clmn]
                    arr[2,clmn]=arr[rowlocation[0],clmn]+arr[rowlocation[1],clmn]
                    arr[1,clmn]=0
                    arr[0,clmn]=0

                else:
                    arr[3,clmn]=arr[rowlocation[2],clmn]
                    arr[2,clmn]=arr[rowlocation[1],clmn]
                    arr[1,clmn]=arr[rowlocation[0],clmn]
                    arr[0,clmn]=0

            elif(len(rowlocation)==4):
                if arr[rowlocation[0],clmn]==arr[rowlocation[1],clmn] and arr[rowlocation[2],clmn]==arr[rowlocation[3],clmn]:
                    arr[3,clmn]=arr[rowlocation[2],clmn]+arr[rowlocation[3],clmn]
                    arr[2,clmn]=arr[rowlocation[0],clmn]+arr[rowlocation[1],clmn]
                    arr[1,clmn]=0
                    arr[0,clmn]=0

                elif arr[rowlocation[2],clmn]==arr[rowlocation[3],clmn]:
                    arr[3,clmn]=arr[rowlocation[2],clmn]+arr[rowlocation[3],clmn]
                    arr[2,clmn]=arr[rowlocation[1],clmn]
                    arr[1,clmn]=arr[rowlocation[0],clmn]
                    arr[0,clmn]=0
                    
                elif arr[rowlocation[1],clmn]==arr[rowlocation[2],clmn]:
                    arr[3,clmn]=arr[rowlocation[3],clmn]
                    arr[2,clmn]=arr[rowlocation[1],clmn]+arr[rowlocation[2],clmn]
                    arr[1,clmn]=arr[rowlocation[0],clmn]
                    arr[0,clmn]=0
                    
                elif arr[rowlocation[0],clmn]==arr[rowlocation[1],clmn]:
                    arr[3,clmn]=arr[rowlocation[3],clmn]
                    arr[2,clmn]=arr[rowlocation[2],clmn]
                    arr[1,clmn]=arr[rowlocation[0],clmn]+arr[rowlocation[1],clmn]
                    arr[0,clmn]=0

                else:
                    arr[3,clmn]=arr[rowlocation[3],clmn]
                    arr[2,clmn]=arr[rowlocation[2],clmn]
                    arr[1,clmn]=arr[rowlocation[1],clmn]
                    arr[0,clmn]=arr[rowlocation[0],clmn]
    createrandom()

In [18]:
arr=np.zeros((4,4), dtype=int)

In [19]:
createrandom()
print(arr)
while True:
    start()
    print(arr)

[[0 0 0 0]
 [0 0 2 0]
 [0 0 0 0]
 [0 0 0 0]]
Left: l , Right: r , Up: u , Down: d | Please Select:l
[[0 0 0 0]
 [2 0 0 0]
 [0 0 0 0]
 [0 0 0 2]]
Left: l , Right: r , Up: u , Down: d | Please Select:l
[[0 0 0 0]
 [2 2 0 0]
 [0 0 0 0]
 [2 0 0 0]]
Left: l , Right: r , Up: u , Down: d | Please Select:l
[[0 0 0 0]
 [4 0 2 0]
 [0 0 0 0]
 [2 0 0 0]]
Left: l , Right: r , Up: u , Down: d | Please Select:l
[[0 0 0 0]
 [4 2 0 0]
 [0 0 0 0]
 [2 0 2 0]]
Left: l , Right: r , Up: u , Down: d | Please Select:r
[[0 0 0 0]
 [0 0 4 2]
 [0 0 0 0]
 [2 0 0 4]]
Left: l , Right: r , Up: u , Down: d | Please Select:u
[[2 0 4 2]
 [0 2 0 4]
 [0 0 0 0]
 [0 0 0 0]]
Left: l , Right: r , Up: u , Down: d | Please Select:d
[[0 0 0 0]
 [0 0 0 0]
 [2 0 0 2]
 [2 2 4 4]]
Left: l , Right: r , Up: u , Down: d | Please Select:l
[[0 0 0 0]
 [0 2 0 0]
 [4 0 0 0]
 [4 8 0 0]]
Left: l , Right: r , Up: u , Down: d | Please Select:u
[[8 2 2 0]
 [0 8 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Left: l , Right: r , Up: u , Down: d | Please Select:d


SystemExit: 1